mixed-port: 7890
redir-port: 7892
external-controller: 0.0.0.0:9999
allow-lan: true
log-level: warning
ipv6: false
keep-alive-idle: 15

sniffer:
  enable: true
  sniffing:
    - tls
    - http

proxy-providers:
  subscription:
    type: http
    url: https://www.cmsub.com/subscribe/WUK1BZDNN7ICBIIB?clash=ssr&trojan
    interval: 3600
    path: ./providers/subscription.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 自动选择, DIRECT], use: [subscription], filter: "(?i)gRPC"}
  - {name: ♻️ 自动选择, type: url-test, tolerance: 100, interval: 600, use: [subscription], filter: "(?i)gRPC"}
  - {name: ⚡ 游戏自动测速, type: url-test, tolerance: 50, interval: 300, use: [subscription], filter: "(?i)(Japan|Korea|Taiwan|日本|韩国|台灣|台湾|JP|KR|TW)"}

rules:
 - GEOIP,CN,DIRECT
 - MATCH,🚀 节点选择
